
version: '3.8'


services:
  mysql-db:
    image: mysql:8.0

    container_name: board_container

    restart: always
    
    environment:
      MYSQL_ROOT_PASSWORD: board 
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: board
      
    ports:
      - "3306:3306"
      
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
